Sign_in_with_Email =//a[text() = 'Sign in with Email']
Email = //input[@id = 'emailaddress']
Password = //input[@id = 'password']
Remember_tik = //input[@id = 'basic_checkbox_1']
Submit = //button[@type = 'submit']
